config/routes.rb
Rails.application.routes.draw do
  



  

  resources :news_blogs

  resources :travel_blogs

  resources :drink_blogs

  resources :eat_blogs

  

  devise_for :users
  root 'display#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/drink_blog.rb
class DrinkBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	 
end

app/models/eat_blog.rb
class EatBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
		 
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/news_blog.rb
class NewsBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/travel_blog.rb
class TravelBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "700x500>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
	def index
		@eat_blogs = EatBlog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
		@drink_blogs = DrinkBlog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
		@travel_blogs = TravelBlog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
		@news_blogs = NewsBlog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 1)
		
	end

  
end

app/controllers/travel_blogs_controller.rb
class TravelBlogsController < ApplicationController
  before_action :set_travel_blog, only: [:show, :edit, :update, :destroy]

  def index
    @travel_blogs = TravelBlog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
    
   end

  def show
    @travel_blog = TravelBlog.find(params[:id])
  end

  def new
    authorize! :new, @travel_blog, :message => 'Not authorized as an administrator.'
    @travel_blog = TravelBlog.new
  end

  def edit
  end

  def create
    @travel_blog = TravelBlog.new(travel_blog_params)
    if @travel_blog.save
      redirect_to root_path
    end
  end

  def update
    if @travel_blog.update(travel_blog_params)
    redirect_to root_path, notice: 'Blog was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @travel_blog.destroy
    redirect_to root_path
  end

  private
    def set_travel_blog
      @travel_blog = TravelBlog.find(params[:id])
    end

    def travel_blog_params
      params.require(:travel_blog).permit(:title, :paragraph1, :paragraph2, :paragraph3, :paragraph4, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/drink_blogs_helper.rb
module DrinkBlogsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/eat_blogs_helper.rb
module EatBlogsHelper
end

app/helpers/eats_helper.rb
module EatsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/news_blogs_helper.rb
module NewsBlogsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/travel_blogs_helper.rb
module TravelBlogsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/travel_blogs/_form.html.erb
<%= simple_form_for(@travel_blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :image %>
    <%= f.input :paragraph1 %>
    <%= f.input :paragraph2 %>
    <%= f.input :paragraph3 %>
    <%= f.input :paragraph4 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/travel_blogs/edit.html.erb
<h1>Editing travel_blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel_blog %> |
<%= link_to 'Back', travel_blogs_path %>

app/views/travel_blogs/index.html.erb
<%= link_to 'New Travel blog', new_travel_blog_path %>

<div id="owl-demo" class="owl-carousel owl-theme">
  <% @travel_blogs.each do |travel_blog| %>
    <div class="item">
      <%= link_to image_tag(travel_blog.image.url(:medium)), travel_blog %>
      <h3>Travel </h3>
      <h2><%= travel_blog.title %></h2>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="travel_blogs" id="transitions-enabled">
    <% @travel_blogs.each do |travel_blog| %>
      <div class="box panel panel-default">
        <td><%= link_to image_tag(travel_blog.image.url(:medium)), travel_blog %></td>
        <h3>Travel </h3>
        <h2><%= travel_blog.title %></h2>
      </div>
    <% end %>
  </div>
</div>




<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

</div>

app/views/travel_blogs/new.html.erb
<h1>New travel_blog</h1>

<%= render 'form' %>

<%= link_to 'Back', travel_blogs_path %>

app/views/travel_blogs/show.html.erb
<section class="top">
	<%= image_tag @travel_blog.image.url %>
  	<h2 class="wide">Travel</h2>
  	<h3 class="wide"><%= @travel_blog.title %></h3>

<div class="max-wide has-padding">
	<p><%= @travel_blog.paragraph1 %></p>
	<p><%= @travel_blog.paragraph2 %></p>
	<p><%= @travel_blog.paragraph3 %></p>
	<p><%= @travel_blog.paragraph4 %></p>


<%= link_to 'Edit', edit_travel_blog_path(@travel_blog) %> |
<%= link_to 'Back', travel_blogs_path, class: "btn-primary btn-lg" %>
  </div>





</section>