config/routes.rb
Rails.application.routes.draw do
  



  

  resources :news_blogs

  resources :travel_blogs

  resources :drink_blogs

  resources :eat_blogs

  

  devise_for :users
  root 'display#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/drink_blog.rb
class DrinkBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	 
end

app/models/eat_blog.rb
class EatBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
		 
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/news_blog.rb
class NewsBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/travel_blog.rb
class TravelBlog < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :large => "700x500>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/drink_blogs_helper.rb
module DrinkBlogsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/eat_blogs_helper.rb
module EatBlogsHelper
end

app/helpers/eats_helper.rb
module EatsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/news_blogs_helper.rb
module NewsBlogsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/layouts/_footer.html.erb
<section class="footer">
  <div class="row">
      <div class="col-md-3 col-sm-3">
          <h5>Stay in the know on where to go</h5>
          <h6>Sign up for our e-newsletter</h6>
            <div class="form-group email">
                    <label class="sr-only" for="email">Email</label>
                    <input id="email" type="email" placeholder="johndoe@email.com">
            </div><!--//form-group-->
                    <button type="submit" class="btn btn-primary">Sign Up</button>
      </div>
    

      <div class="col-md-3 col-sm-3">
          <h5>Categories</h5>
            <ul>
              <li><%= link_to "Eat", eat_blogs_path %> </li>
              <li><%= link_to "Drink", drink_blogs_path %> </li>
              <li><%= link_to "Travel", travel_blogs_path %></li>
              <li><%= link_to "News",  news_blogs_path %> </li>
            </ul>
      </div>

      <div class="col-md-3 col-sm-3"> 
          <h5>Social</h5>
            <li><a href="https://www.facebook.com/getbeen" target="_blank">Facebook</a></li>
            <li><a href="http://instagram.com/getbeen/" target="_blank">Instagram</a> </li>
            <li><a href="https://twitter.com/BeenMobileApp" target="_blank">Twitter</a></li>
            <li><a href="http://www.pinterest.com/getbeen" target="_blank">Pinterest</a></li>  
      </div>

      <div class="col-md-3 col-sm-3">
          <h5>About Been</h5>
          <h6>Been is a soon-to-launch mobile app that helps you find places to go based on friends' recommendations and keeps track of where you've been.</h6> 
      </div>

    </div>

    
  


  <div class="footer-content-container-slim container-semi-opaque">
      <div class="container page-container">
        <div class="row text-muted text-center row-space-8 row-space-top-6 copy-wrap">
          <div id="copyright">© Been 2014</div>
        </div>
      </div>
  </div>

</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav">
    
    <li><%= link_to "Been ", root_path, class: "navbar-brand" %> </li>
  </ul>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog |", root_path, class: "navbar-brand" %> </li>
      <li><%= link_to "Eat", eat_blogs_path %></li>
      <li><%= link_to "Drink", drink_blogs_path %></li>
      <li><%= link_to "Travel", travel_blogs_path %></li>
      <li><%= link_to "News", news_blogs_path %></li>  
      
    </ul>
  </div><!-- /.navbar-collapse -->
 </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getbeen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	

<%= yield %>

<div class="push"></div>

<%= render 'layouts/footer' %>
</body>
</html>